<a href="https://colab.research.google.com/github/taniagoa/Tercer-challenge-CD-Telecom-X-parte2/blob/main/telecomXparte2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
datos=pd.read_csv('/content/datos_tratados.csv')
datos.head()

,IDcliente,evasion,genero,adultoMayor,pareja,dependientes,permanencia,telefonoFijo,MultipleLines,internet,...,DeviceProtection,servicioTecnico,StreamingTV,StreamingMovies,contrato,reciboElectronico,metodoDePago,cargoMensual,cargoTotal,cuentasDiarias
0,0002-ORFBO,0,Female,0,Yes,Yes,9,Yes,No,DSL,...,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.30,5.466667
1,0003-MKNFE,0,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.40,4.991667
2,0004-TLHLJ,1,Male,0,No,No,4,Yes,No,Fiber optic,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85,6.158333
3,0011-IGKFF,1,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85,8.166667
4,0013-EXCHZ,1,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.40,6.991667

In [12]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   IDcliente          7032 non-null   object
 1   evasion            7032 non-null   int64
 2   genero             7032 non-null   object
 3   adultoMayor        7032 non-null   int64
 4   pareja             7032 non-null   object
 5   dependientes       7032 non-null   object
 6   permanencia        7032 non-null   int64
 7   telefonoFijo       7032 non-null   object
 8   MultipleLines      7032 non-null   object
 9   internet           7032 non-null   object
 10  OnlineSecurity     7032 non-null   object
 11  OnlineBackup       7032 non-null   object
 12  DeviceProtection   7032 non-null   object
 13  servicioTecnico    7032 non-null   object
 14  StreamingTV        7032 non-null   object
 15  StreamingMovies    7032 non-null   object
 16  contrato           7032 non-null   object
 17  reciboElectronico  7032 non-null   object
 18  metodoDePago       7032 non-null   object
 19  cargoMensual       7032 non-null   float64
 20  cargoTotal         7032 non-null   float64
 21  cuentasDiarias     7032 non-null   float64
dtypes: float64(3), int64(3), object(16)
memory usage: 1.2+ MB

Teniendo en cuenta la primera parte de telecomX podemos identificar las columnas que no tienen relevancia para evaluar la evasion de clientes, estas columnas seran eliminadas para evitar que afecten al modelo

In [14]:
datos2=datos.drop(columns=['IDcliente','genero','adultoMayor','pareja','dependientes','reciboElectronico','metodoDePago'])
datos2.head()

,evasion,permanencia,telefonoFijo,MultipleLines,internet,OnlineSecurity,OnlineBackup,DeviceProtection,servicioTecnico,StreamingTV,StreamingMovies,contrato,cargoMensual,cargoTotal,cuentasDiarias
0,0,9,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,65.6,593.30,5.466667
1,0,9,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,59.9,542.40,4.991667
2,1,4,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,73.9,280.85,6.158333
3,1,13,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,98.0,1237.85,8.166667
4,1,3,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,83.9,267.40,6.991667

In [22]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder
X=datos2.drop('evasion',axis=1)
y=datos2['evasion']
columnas=X.columns
one_hot=make_column_transformer((OneHotEncoder(drop='if_binary'),['internet','contrato','telefonoFijo','MultipleLines']),remainder='passthrough',sparse_threshold=0,force_int_remainder_cols=False)
X=one_hot.fit_transform(X)
one_hot.get_feature_names_out(columnas)

array(['onehotencoder__internet_DSL',
       'onehotencoder__internet_Fiber optic',
       'onehotencoder__internet_No',
       'onehotencoder__contrato_Month-to-month',
       'onehotencoder__contrato_One year',
       'onehotencoder__contrato_Two year',
       'onehotencoder__telefonoFijo_Yes',
       'onehotencoder__MultipleLines_No',
       'onehotencoder__MultipleLines_No phone service',
       'onehotencoder__MultipleLines_Yes', 'remainder__permanencia',
       'remainder__OnlineSecurity', 'remainder__OnlineBackup',
       'remainder__DeviceProtection', 'remainder__servicioTecnico',
       'remainder__StreamingTV', 'remainder__StreamingMovies',
       'remainder__cargoMensual', 'remainder__cargoTotal',
       'remainder__cuentasDiarias'], dtype=object)